puts "Add a student profile to the list. What's his/her name?".center(72)
puts "What country are they from?".center(43)
puts "What's his or her age?".center(39)
puts "What's his or her age?".center(39)
puts "What cohort are they in? (month)".center(48)
puts "Add another student's profilf his/her name.".center(60)
puts "or press ENTER to print out the whole list".center(58)
puts "The students of Makers Academy".center(47)
puts "-------------".center(30)
puts "-------------".center(30)
puts "Overall, we have 5 great students".center(50)
puts "What cohort do you want to see?".center(47)
puts "This is an alien!".center(33)
